### ISSUE TITLE
大牛先生,求前端页面更新

### ISSUE THREAD

**Issue by 1131057908** [DDDDanny/ExamOnline-Server#1]
66666666666666666666666666666666666666666

**Comment by w4sevens** [comment]
前端没有，后台也没有啊，崩溃

**Comment by w4sevens** [comment]
数据库自己可以生成吧

**Comment by DDDDanny** [comment]
> 数据库自己可以生成吧

对的，通过Django的magrate

**Comment by DDDDanny** [comment]
- 暂时没有时间做前端页面
- 数据库可以通过Django的magrate生成

**Comment by DDDDanny** [comment]
- 前端页面暂时没有做
- 数据库可以通过Django的magrate生成
